import { ClerkProvider, useUser } from '@clerk/nextjs'
import { type Metadata } from 'next'
import '../styles/globals.css'
import Navbar from '@/components/layout/Navbar'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-slate-100 font-sans">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
