import { ClerkProvider, useUser } from '@clerk/nextjs'
import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/app-sidebar'
import Header from '@/components/layout/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen bg-white text-slate-800 font-sans">
          <div className="flex">
            {/* Sidebar */}
            <SidebarProvider>
              <AppSidebar />
              <SidebarTrigger />
            </SidebarProvider>

            <div className="flex flex-col w-full">
              <Header />
              <main className="flex-1 p-4">{children}</main>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
