import { ClerkProvider, useUser } from '@clerk/nextjs'
import { type Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'




export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function DashboardLayout({children}: Readonly<{children: React.ReactNode}>) {

  return (
   <div>
    <nav></nav>
    <section>{children}</section>
   </div>
  )
}
